notifications:
  email: false
  slack:
    rooms:
      secure: S3xDhrrLgQ1DSBgc42M9wkJzmqYlv/FSeKhcOxDVspy8s/N2N4z4JCGpuX3RYIPEHNIaao9gTvQJ5Ddoq5hCppXncyKsmH4NvDVQ1JdjTRk5KXp6SC0mJvJ7Vh4pKhcpJu87sh9dZs9Io6VqqG/bGpcjt9SFgVz/n24DPKgeREa351GorhncFmnG3ZtItHGe5a7n5V9sM3g5uLUf0ELPew6iPvkyx5xNvyMfMrgcJDbXKHQR6S5xvp7Pw/GkXGVR7d1nQElKMsDOlEiui+l2ctRFo0ZnNGoVzvLGKygkw717Q6k215Gq7x/eZI5//Kidwxra0ks7NYhYhzayRiy+pJ2ZYH3N8c5KL6xbVzyNn8LpP733Ra48oJZK+yjk77TAIkwvBsoH0p1Hc1fi12fdgrhACHa48zy/ILMcnGILfX5BOjVwpPy2dUbiKQHmClrq4Fe+t9vK11wqEjJr/bm2WfmbqEudWn3Kb1Vpk5ZohNZuhXcqJ/PdT9ns9ac8jNHxP3mAiCulOQbRNFq95ZjYQuMscKzlw18WUNyfi/5hsMCKgi78Kbg5Bzia1SieF0w+uo3qHDNIEPiuQevrSc0zGLUaPn+G4O08tx75Gxjg23/leBvn36qv2rXG1+RjL7saj00S2sTSKEB9rXWf8unE19Rh2gXDg4Asxyr63nOLBBI=
    on_success: always
    on_failure: always

stages:
- name: BUILD
- name: TEST
- name: DEPLOY
- name: ANDROID
- name: IOS

jobs:
  include:

  - stage: BUILD
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    install: true
    script:
    - bash .travis.build.sh
    deploy:
      skip_cleanup: true
      provider: s3
      access_key_id: "$S3_ACCESS_KEY"
      secret_access_key: "$S3_SECRET_ACCESS_KEY"
      bucket: kapp-builds
      local_dir: dist
      upload_dir: "$TRAVIS_BUILD_NUMBER/dist"
      on:
        all_branches: true

  - stage: TEST
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    addons:
      code_climate:
        repo_token: 19d3ef0c5e4541c913514b7a3a3825829e5e354f08dc39fd2c03b7898958d597
    install:
    - npm install -g codeclimate-test-reporter
    script:
    - bash .travis.test.sh
    after_script:
    - codeclimate-test-reporter < server-coverage/lcov.info
    deploy:
      - provider: s3
        skip_cleanup: true
        access_key_id: "$S3_ACCESS_KEY"
        secret_access_key: "$S3_SECRET_ACCESS_KEY"
        bucket: aktnmap-builds
        local_dir: server-coverage
        upload_dir: "$TRAVIS_BUILD_NUMBER/server-tests/coverage"
        on:
          all_branches: true
      - provider: s3
        skip_cleanup: true
        access_key_id: "$S3_ACCESS_KEY"
        secret_access_key: "$S3_SECRET_ACCESS_KEY"
        bucket: aktnmap-builds
        local_dir: client-screenshots
        upload_dir: "$TRAVIS_BUILD_NUMBER/client-tests/screenshots"
        on:
          all_branches: true

  - stage: DEPLOY
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    install: true
    script:
    - bash .travis.deploy.sh

  - stage: ANDROID
    language: android
    sudo: false
    jdk: oraclejdk8
    android:
      components:
      - tools
      - tools  # Include again to work around travis not using the latest, see: https://github.com/travis-ci/travis-ci/issues/6193
      - platform-tools
      - build-tools-27.0.3
      - android-27
    cache:
      directories:
      # Android SDK
      - $HOME/android-sdk-dl
      - $HOME/android-sdk
    licenses:
      - '.+'
    before_install:
    - nvm install 8
    - yes | sdkmanager "platforms;android-27"
    install:
    - pip install --user awscli
    - npm install -g cordova
    - npm install -g cross-env
    - gem install fastlane
    script:
    - bash .travis.android.sh

  - stage: IOS
    language: objective-c
    osx_image: xcode8.3
    sudo: required
    before_install:
    - nvm install 8
    install:
    - brew install awscli
    - npm install -g cordova
    - npm install -g ios-deploy    
    - npm install -g cross-env
    - gem install fastlane        
    script:
    - bash .travis.ios.sh
