version: '3.3'

services:
  app:
    image: kalisio/${APP}:${VERSION_TAG}
    env_file:
      - ../.env    
    build:
      context: ../.
      dockerfile: dockerfile
      args:
        APP: ${APP}
        BRANCH: ${BRANCH}
        FLAVOR: ${FLAVOR}
        MANIFEST: ${MANIFEST}        
        BUILD_NUMBER: ${BUILD_NUMBER}
        
            