version: '3.3'

services:
  app:
    environment:
      - DEBUG=
      - DB_URL=mongodb://mongodb:27017/${APP}
    working_dir: /opt/${APP}
    depends_on:
      - mongodb
    volumes:
      - ../coverage:/opt/${APP}/api/coverage
      - ../src:/opt/${APP}/api/src
    command: [ "npm", "run", "test:server" ]
