version: '3.3'

services:
  mocha:
    environment:
      - DEBUG=
      - DB_URL=mongodb://mongodb:27017/${APP}
    working_dir: /opt/${APP}
    volumes:
      - ./server-coverage:/opt/${APP}/api/coverage
    command: [ "npm", "run", "test:server" ]
