version: '3.3'

services:
  app:
    image: kalisio/${APP}:${VERSION_TAG}
    environment:
      - APP_SECRET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - BUILD_NUMBER
      - NODE_APP_INSTANCE=${FLAVOR}
      - DB_URL
    networks:
      - app
      - cluster

networks:
  app:
  cluster:
    external:
      name: ${DOCKER_NETWORK}
